# Original: https://github.com/VROOM-Project/vroom-docker/blob/master/Dockerfile
# I made some tweaks. Credits to the owner!
FROM debian:trixie-slim AS builder
LABEL maintainer=nils@gis-ops.com

WORKDIR /

RUN echo "Updating apt-get and installing dependencies..." && \
    apt-get -y update && \
    apt-get -y install \
    git-core \
    build-essential \
    g++-13 \
    gcc-13 \
    libssl-dev \
    libasio-dev \
    libglpk-dev \
    pkg-config && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

ARG VROOM_EXPRESS_RELEASE=master

# clone here, since the runner image doesn't have git installed
RUN echo "Cloning and installing vroom-express release/branch ${VROOM_EXPRESS_RELEASE}..." && \
    git clone --branch $VROOM_EXPRESS_RELEASE --single-branch https://github.com/VROOM-Project/vroom-express.git

ARG VROOM_RELEASE=master

RUN echo "Cloning and installing vroom release/branch ${VROOM_RELEASE}..." && \
    git clone --branch $VROOM_RELEASE --single-branch --recurse-submodules https://github.com/VROOM-Project/vroom.git && \
    cd vroom && \
    make -C /vroom/src -j$(nproc)

FROM debian:trixie-slim AS runstage

RUN echo "Installing Node.js and dependencies..." && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
        && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y --no-install-recommends \
        nodejs \
        libssl3 \
        libglpk40 \
        && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /vroom-express/. /vroom-express
COPY --from=builder /vroom/bin/vroom /usr/local/bin

WORKDIR /vroom-express

# Use the config.yml file from the host
COPY vroom-config.yml /vroom-express/config.yml

RUN npm config set loglevel error && \
    npm install && \
    # To share the config.yml & access.log file with the host
    mkdir /conf

HEALTHCHECK --start-period=10s CMD curl --fail -s http://localhost:3000/health || exit 1

EXPOSE 3000
CMD ["npm", "start"]